package pl.ninebits.qa.eurocash.site.ehurt.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ProductsName {

  PRODUCT_NAME1("WODKA KRUPNIK PREMIUM 40% 700ML MBWS"),
  PRODUCT_NAME2("OLEJ KUJAWSKI 1L KRUSZWICA"),
  PRODUCT_NAME3("KAWA MIELONA TCHIBO FAMILY PRAS 250G"),
  PRODUCT_NAME4("MARGARYNA DELMA EXTRA 450G UPFIELD"),
  PRODUCT_NAME5("PIWO HARNAS 500ML 4-PAK CARLSBERG"),
  PRODUCT_NAME6("WODKA ZUBROWKA BIALA 40% 700ML CEDC"),
  PRODUCT_NAME7("WODA ZYWIEC ZDROJ NGAZ 1,5L PET"),
  PRODUCT_NAME8("PIWO KASZTELAN JASNE PELNE 500ML 4-PAK CARLSBERG PUSZ"),
  PRODUCT_NAME9("NAPOJ ENERGET TIGER CLASSIC 24*250ML MASPEX PUSZ"),
  PRODUCT_NAME10("MLEKO UHT LACIATE ZOLTE 2% 1L MLEKPOL"),
  PRODUCT_NAME11("NAPOJ HOOP COLA GAZ 2L PET"),
  PRODUCT_NAME12("PTASIE MLECZKO WANILIOWE 380G WEDEL"),
  PRODUCT_NAME13("MLEKO UHT LACIATE CZERWONE 3,2% 1L MLEKPOL"),
  PRODUCT_NAME14("MARGARYNA MR SLYNNE ROSLINNE 250G KRUSZWICA KUB"),
  PRODUCT_NAME15("PIWO WARKA JASNE PELNE 500ML GZ BUT ZW"),
  PRODUCT_NAME16("KAWA ROZPUSZCZALNA TCHIBO FAMILY CLASSIC 200G"),
  PRODUCT_NAME17("OLEJ OLEO RZEPAKOWY 900ML KRUSZWICA"),
  PRODUCT_NAME18("MARGARYNA KASIA BEZ LAKTOZY 250G UPFIELD"),
  PRODUCT_NAME19("WAFEL PRINCE POLO CLASSIC XXL 50G MONDELEZ"),
  PRODUCT_NAME20("KONCENTRAT POMIDOROWY PUDLISZKI 200G HEINZ SLOIK"),
  PRODUCT_NAME21("SEREK WIEJSKI OSM PIATNICA 200G"),
  PRODUCT_NAME22("WODKA WYBOROWA 40% 700ML"),
  PRODUCT_NAME23("SMIETANA OSM PIATNICA 18% 200ML");

  private String namesProduct;
}

